"""Generate remediation artifacts (CLI / Terraform) from a finding. Deterministic, no AWS calls,
and never executed — the operator reviews and runs them. Available in artifacts + guarded_write.
"""
from __future__ import annotations

from finops_core.schemas.remediation import Artifact

_HEADER = "# Generated by AWS FinOps Agent — REVIEW before running. This is advisory.\n"


def generate_artifact(finding: dict, fmt: str = "cli") -> Artifact:
    action = (finding.get("action") or "").lower()
    rid = finding.get("resource_id") or "<resource-id>"
    region = finding.get("region") or "<region>"
    title = finding.get("title", "remediation")
    save = finding.get("monthly_savings", 0)
    note = f"# {title}  (est. savings ${save}/mo, risk={finding.get('risk', '?')})\n"

    if fmt == "terraform" and action in ("create_or_update_budget", "budget"):
        content = (_HEADER + note +
                   'resource "aws_budgets_budget" "monthly" {\n'
                   '  name         = "finops-monthly"\n'
                   '  budget_type  = "COST"\n'
                   '  limit_amount = "100"\n'
                   '  limit_unit   = "USD"\n'
                   '  time_unit    = "MONTHLY"\n}\n')
        return Artifact("terraform", "budget.tf", content, f"Terraform for: {title}")

    if action == "terminate":
        body = (f"# Idle instance — verify it is safe to terminate first.\n"
                f"aws ec2 describe-instances --instance-ids {rid} --region {region}\n"
                f"# aws ec2 terminate-instances --instance-ids {rid} --region {region}\n")
    elif action in ("modify", "rightsize"):
        body = (f"# Rightsize {rid}: stop, change type to {finding.get('recommended', '<type>')}, start.\n"
                f"# aws ec2 stop-instances --instance-ids {rid} --region {region}\n"
                f"# aws ec2 modify-instance-attribute --instance-id {rid} "
                f"--instance-type {finding.get('recommended', '<type>')} --region {region}\n"
                f"# aws ec2 start-instances --instance-ids {rid} --region {region}\n")
    elif action in ("purchase-savings-plan", "purchase-ri"):
        body = ("# Commitment purchase — review term/payment, then buy in the console or via:\n"
                "# aws savingsplans create-savings-plan ...  (or RI: aws ec2 purchase-reserved-instances-offering ...)\n")
    elif action == "review":
        body = ("# Trusted Advisor flagged resources — review the check in the console and act per finding.\n")
    else:
        body = (f"# {title}\n# Review the recommendation and apply the change for {rid} in {region}.\n")

    return Artifact("cli", "remediation.sh", _HEADER + note + body, f"CLI script for: {title}")
